#!/bin/bash
ttp=word2vec
for grup in artykuly_bbc datasets_zespol2 datasets_zespol4_v1 datasets_zespol4_v2 sample_dataset zespol5 ; do 
	mkdir zbior$grup
	python3 scripts/$ttp.py --input-dir datasets/$grup/ --output-dir zbior$grup/
done

