#!/bin/bash
echo "what is the text to point converting method?"
read ttp
echo "grupa;text2num;red-method;dim;classifier;result" > ~/Dokumenty/repos/ZPS2019/dane2.txt
for grup in artykuly_bbc datasets_zespol2 datasets_zespol4_v1 datasets_zespol4_v2 sample_dataset zespol5 ; do 
	mkdir ~/Dokumenty/repos/ZPS2019/zbior$grup
	python3 ~/Dokumenty/repos/ZPS2019/scripts/$ttp.py --input-dir ~/Dokumenty/repos/ZPS2019/datasets/$grup/ --output-dir ~/Dokumenty/repos/ZPS2019/zbior$grup/
	for red in pca kernelpca ica lda nmf ; do
		mkdir ~/Dokumenty/repos/ZPS2019/zbior$grup/$red
		for dim in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 25 50 100 200; do
			mkdir ~/Dokumenty/repos/ZPS2019/zbior$grup/$red/$dim
			python3 ~/Dokumenty/repos/ZPS2019/scripts/dim_red.py --input-dir ~/Dokumenty/repos/ZPS2019/zbior$grup/ --output-dir ~/Dokumenty/repos/ZPS2019/zbior$grup/$red/$dim --method $red --n-components $dim
			for clas in SVM decisiontree gaussian_bayes_classifier knn ; do
				echo "$grup"";""$ttp"";""$red"":""$dim"";""$clas"";" >> ~/Dokumenty/repos/ZPS2019/dane2.txt
				python3 ~/Dokumenty/repos/ZPS2019/scripts/$clas.py --input-dir ~/Dokumenty/repos/ZPS2019/zbior$grup/$red/$dim >> ~/Dokumenty/repos/ZPS2019/dane2.txt
				sleep 4
			done
		done
	done
	red=tsne
	mkdir ~/Dokumenty/repos/ZPS2019/zbior$grup/$red
	for dim in 1 2 3 ; do
		mkdir ~/Dokumenty/repos/ZPS2019/zbior$grup/$red/$dim
		python3 ~/Dokumenty/repos/ZPS2019/scripts/dim_red.py --input-dir ~/Dokumenty/repos/ZPS2019/zbior$grup/ --output-dir ~/Dokumenty/repos/ZPS2019/zbior$grup/$red/$dim --method $red --n-components $dim
		for clas in SVM decisiontree gaussian_bayes_classifier knn ; do
			echo "$grup"";""$ttp"";""$red"":""$dim"";""$clas"";" >> ~/Dokumenty/repos/ZPS2019/dane2.txt
			python3 ~/Dokumenty/repos/ZPS2019/scripts/$clas.py --input-dir ~/Dokumenty/repos/ZPS2019/zbior$grup/$red/$dim >> ~/Dokumenty/repos/ZPS2019/dane2.txt
		done
	done
done

